### ISSUE TITLE
Feedback Task Pertemuan 3

### ISSUE THREAD

**Issue by aufaroot18** [aldimahardiansyah/front-end#1]
## Perbaikan:

- Pada fungsi `find` di `findByName`, gunakan operator logika untuk membandingkan data, bukan menggunakan operator assignment.

## Hal yang bisa ditingkatkan:

- Pada fungsi `map` di `formatUser`, dapat menggunakan spread operator untuk mengupdate object. Ex: ``{ ...user, name: `${title}. ${user.name}` }``
- Return pada arrow function bisa dipersingkat menjadi sebaris

**Comment by aldimahardiansyah** [comment]
Ok done kak

**Comment by aufaroot18** [comment]
Sorry, maksudnya operator perbandingan `==` untuk mencari data berdasarkan `name`.

Thanks.

**Comment by aldimahardiansyah** [comment]
bukannya udah bener kayak gini kak? 
![image](https://user-images.githubusercontent.com/41710133/162602263-0061c10d-8c86-4936-a9aa-add01d795668.png)

**Comment by aufaroot18** [comment]
Yap, benar begitu.

Jika name user sama dengan parameter name, maka kembalikan data yang dicari.

**Comment by aldimahardiansyah** [comment]
Okee

Thanks kak

**Comment by aufaroot18** [comment]
Welcome.
